name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1


      - name: Build Pages
        run: |
          # Build Storybook
          npm ci
          npm run build-storybook
          cd docs
          npm ci
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Pages Action"
          npm run build
          mv ../storybook-static ./build/storybook
          npm run deploy -- --skip-build
        env:
          GIT_USER: ${{ secrets.ACCESS_TOKEN }}
